### ISSUE TITLE
All broken

### ISSUE THREAD

**Issue by ezhimakov** [artsurkan/sfk-test#1]
`docker -v && docker-compose -v` 
>Docker version 19.03.8, build afacb8b7f0
docker-compose version 1.25.4, build 8d51620a

` docker logs task-web`
> my-app2@0.1.0 start /usr/src/app
> craco start
sh: craco: not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! my-app2@0.1.0 start: `craco start`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the my-app2@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?`

` docker logs task-api`
> api@0.1.0 migrate /usr/src/app
sequelize-cli db:migrate
sh: sequelize-cli: not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! api@0.1.0 migrate: `sequelize-cli db:migrate`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the api@0.1.0 migrate script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-03-25T06_09_32_996Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! api@0.1.0 dev: `npm run migrate && nodemon --exec ts-node -r tsconfig-paths/register ./src`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the api@0.1.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

`docker-compose ps`
>ERROR: The Compose file './docker-compose.yml' is invalid because:
services.api.ports is invalid: Invalid port ":", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
services.web.ports is invalid: Invalid port ":", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
services.db.ports is invalid: Port ranges don't match in length`

**Comment by artsurkan** [comment]
@ezhimakov sorry, fixed, everything might be a little complicated than meets the eye
